-- ============================================================================
-- 02_create_schema_tables.sql
-- Objectif:
--   Creer les tables, contraintes et index du schema TuniVest.
--
-- IMPORTANT:
-- - Executer ce script connecte en tant que: tunivest_admin
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Table: app_users
-- ---------------------------------------------------------------------------
CREATE TABLE app_users (
  user_id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email                VARCHAR2(150) NOT NULL,
  full_name            VARCHAR2(120),
  phone                VARCHAR2(30),
  salary               NUMBER(12,2) DEFAULT 0,
  risk_profile         VARCHAR2(20) DEFAULT 'moderate' NOT NULL,
  user_role            VARCHAR2(20) DEFAULT 'user' NOT NULL,
  is_active            NUMBER(1) DEFAULT 1 NOT NULL,
  created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_app_users_email UNIQUE (email),
  CONSTRAINT ck_app_users_role CHECK (user_role IN ('user', 'admin')),
  CONSTRAINT ck_app_users_risk CHECK (risk_profile IN ('conservative', 'moderate', 'aggressive')),
  CONSTRAINT ck_app_users_active CHECK (is_active IN (0, 1))
);

-- ---------------------------------------------------------------------------
-- Table: investments
-- ---------------------------------------------------------------------------
CREATE TABLE investments (
  investment_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                 VARCHAR2(160) NOT NULL,
  description          CLOB,
  category             VARCHAR2(40) NOT NULL,
  min_amount           NUMBER(14,2) DEFAULT 0 NOT NULL,
  expected_return_pct  NUMBER(5,2) DEFAULT 0 NOT NULL,
  risk_level           NUMBER(2) DEFAULT 5 NOT NULL,
  duration_months      NUMBER(4) DEFAULT 12 NOT NULL,
  is_active            NUMBER(1) DEFAULT 1 NOT NULL,
  created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_investments_risk CHECK (risk_level BETWEEN 1 AND 10),
  CONSTRAINT ck_investments_active CHECK (is_active IN (0, 1))
);

-- ---------------------------------------------------------------------------
-- Table: portfolio
-- ---------------------------------------------------------------------------
CREATE TABLE portfolio (
  portfolio_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id              NUMBER NOT NULL,
  investment_id        NUMBER NOT NULL,
  units                NUMBER(14,4) DEFAULT 0 NOT NULL,
  purchase_price       NUMBER(14,4) DEFAULT 0 NOT NULL,
  current_value        NUMBER(14,2) DEFAULT 0 NOT NULL,
  purchased_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_portfolio_user FOREIGN KEY (user_id) REFERENCES app_users(user_id),
  CONSTRAINT fk_portfolio_investment FOREIGN KEY (investment_id) REFERENCES investments(investment_id)
);

-- ---------------------------------------------------------------------------
-- Table: recommendations
-- ---------------------------------------------------------------------------
CREATE TABLE recommendations (
  recommendation_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id              NUMBER NOT NULL,
  investment_id        NUMBER NOT NULL,
  score                NUMBER(5,2) DEFAULT 0 NOT NULL,
  reason               VARCHAR2(500),
  is_viewed            NUMBER(1) DEFAULT 0 NOT NULL,
  created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_recommendations_user FOREIGN KEY (user_id) REFERENCES app_users(user_id),
  CONSTRAINT fk_recommendations_investment FOREIGN KEY (investment_id) REFERENCES investments(investment_id),
  CONSTRAINT ck_recommendations_score CHECK (score BETWEEN 0 AND 100),
  CONSTRAINT ck_recommendations_viewed CHECK (is_viewed IN (0, 1))
);

-- ---------------------------------------------------------------------------
-- Table: transactions
-- ---------------------------------------------------------------------------
CREATE TABLE transactions (
  transaction_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id              NUMBER NOT NULL,
  investment_id        NUMBER,
  txn_type             VARCHAR2(30) NOT NULL,
  units                NUMBER(14,4) DEFAULT 0,
  price_per_unit       NUMBER(14,4) DEFAULT 0,
  total_value          NUMBER(14,2) DEFAULT 0,
  status               VARCHAR2(20) DEFAULT 'completed' NOT NULL,
  created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_transactions_user FOREIGN KEY (user_id) REFERENCES app_users(user_id),
  CONSTRAINT fk_transactions_investment FOREIGN KEY (investment_id) REFERENCES investments(investment_id),
  CONSTRAINT ck_transactions_type CHECK (txn_type IN ('buy', 'sell', 'deposit', 'withdrawal', 'dividend'))
);

-- ---------------------------------------------------------------------------
-- Table: market_data
-- ---------------------------------------------------------------------------
CREATE TABLE market_data (
  market_data_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  investment_id        NUMBER NOT NULL,
  price                NUMBER(14,4) DEFAULT 0 NOT NULL,
  change_percent       NUMBER(8,4) DEFAULT 0,
  volume               NUMBER(18,2) DEFAULT 0,
  recorded_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_market_data_investment FOREIGN KEY (investment_id) REFERENCES investments(investment_id)
);

-- ---------------------------------------------------------------------------
-- Table: simulations
-- ---------------------------------------------------------------------------
CREATE TABLE simulations (
  simulation_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id              NUMBER NOT NULL,
  investment_id        NUMBER,
  initial_amount       NUMBER(14,2) DEFAULT 0 NOT NULL,
  duration_months      NUMBER(4) DEFAULT 12 NOT NULL,
  projected_return     NUMBER(14,2) DEFAULT 0,
  projected_value      NUMBER(14,2) DEFAULT 0,
  risk_level           NUMBER(2) DEFAULT 5,
  created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_simulations_user FOREIGN KEY (user_id) REFERENCES app_users(user_id),
  CONSTRAINT fk_simulations_investment FOREIGN KEY (investment_id) REFERENCES investments(investment_id),
  CONSTRAINT ck_simulations_risk CHECK (risk_level BETWEEN 1 AND 10)
);

-- ---------------------------------------------------------------------------
-- Indexes pour performance
-- ---------------------------------------------------------------------------
CREATE INDEX idx_investments_active ON investments(is_active);
CREATE INDEX idx_portfolio_user ON portfolio(user_id);
CREATE INDEX idx_transactions_user_date ON transactions(user_id, created_at);
CREATE INDEX idx_market_data_investment_date ON market_data(investment_id, recorded_at);

-- ---------------------------------------------------------------------------
-- Privileges objets pour roles applicatifs
-- ---------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON app_users TO tunivest_rw_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON investments TO tunivest_rw_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON portfolio TO tunivest_rw_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON recommendations TO tunivest_rw_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON transactions TO tunivest_rw_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON market_data TO tunivest_rw_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON simulations TO tunivest_rw_role;

GRANT SELECT ON app_users TO tunivest_ro_role;
GRANT SELECT ON investments TO tunivest_ro_role;
GRANT SELECT ON portfolio TO tunivest_ro_role;
GRANT SELECT ON recommendations TO tunivest_ro_role;
GRANT SELECT ON transactions TO tunivest_ro_role;
GRANT SELECT ON market_data TO tunivest_ro_role;
GRANT SELECT ON simulations TO tunivest_ro_role;
